### PR TITLE
[IT] Translate `GetState`

### PR DESCRIPTION
**Pull request by alessandroias**
This PR adds `GetState` support to the italian language.

### CODE REVIEW

**Comment by synesthesiam** [comment]
@xraver @auanasgheps are you able to help @alessandroias here?

**Comment by alessandroias** [comment]
Tonight I'm finishing this :)

**Comment by auanasgheps** [comment]
I can't understand where's the error, the CI test is not clear. 

@alessandroias are you done with your changes?

**Comment by alessandroias** [comment]
@auanasgheps @xraver I would love if you could have a look this changes, and tell me what to improve (and why CI checks are not successful). 
Thanks a lot! It's driving me crazy! (I'm sleepy too, I will continue tomorrow).

**Review by auanasgheps — APPROVED** [review]
Your changes look good. I have nothing to change, maybe something will be tweaked after real world usage. However, the CI test are not showing exactly WHY it's failing

**Comment by auanasgheps** [comment]
I updated the branch because it reports it's not updated. Lets see if fixes the error.

**Comment by auanasgheps** [comment]
So, some stuff in `intents/tests/it/cover_HassGetState.yaml` was not properly in place.
There's still an error, but it's different, hurray!

**Comment by auanasgheps** [comment]
What I get is
`Error:  tests/it/cover_HassGetState.yaml: not all sentences have tests (5/7)`

In fact I removed the last two sentences that @alessandroias has added, those are not in the English file. However, if I add them, I get a generic error without explanation.

I cannot find these two sentences in other files, so I don't understand why it complains. 
Alessandro do you know where these sentences are referenced?

**Comment by alessandroias** [comment]
As far as I can understand: nowhere...

**Comment by auanasgheps** [comment]
@synesthesiam can you share some light on the error?

**Comment by auanasgheps** [comment]
@nikito7 thank you!

**Pull request merged**
