### PR TITLE
Update light_HassTurnOn.yaml

### PR DESCRIPTION
**Pull request by Pittermaennchen**
Mein Befehl "Mach die Lichterkette an" hat nicht funktioniert. Also habe ich "mach" und die Artikel hinzugefügt. Bitte um Übernahme.

### CODE REVIEW

**Review by steffenrapp — CHANGES_REQUESTED** [review]
Hi @Pittermaennchen 😃 Unfortunately your changes won't lead to the intended result as you're addressing a `<name>`. So you have to change homeassistant_HassTurnOn and homeassistant_HassTurnOff instead. Also all of your changes are already covered by the `expansion_rules` as they include the relevant articles and "mach".

**Comment by Pittermaennchen** [comment]
> Hi @Pittermaennchen 😃 Unfortunately your changes won't lead to the intended result as you're addressing a `<name>`. So you have to change homeassistant_HassTurnOn and homeassistant_HassTurnOff instead. Also all of your changes are already covered by the `expansion_rules` as they include the relevant articles and "mach".

Thank you for your response!

But why is my Assistant not responding to any of my questions then? The only answer I get is "Entschuldigung, das habe ich nicht verstanden". Shouldn't there be an adequate response and action, if the imperative and articles are already included in the rules?

**Comment by steffenrapp** [comment]
@Pittermaennchen Because you have to extend homeassistant_HassTurnOn and homeassistant_HassTurnOff by "mach[e]" instead 😃 The light files don't recognize the name of your light as they just react to words like "Licht", "Lampe" and so on ... Hope it's clear now.

**Comment by steffenrapp** [comment]
@Pittermaennchen I think you can close this PR as it should now be working with #1373 😃

**Comment by mib1185** [comment]
superseded by #1373

**Pull request closed without merging**
