### PR TITLE
[IT] Add support for HassSetPosition

### PR DESCRIPTION
**Pull request by Sartoric**
Add support for cover position for the Italian language

### CODE REVIEW

**Comment by auanasgheps** [comment]
Looks good, thanks!

**Review by auanasgheps — APPROVED** [review]

**Comment by auanasgheps** [comment]
It's marked as draft: are you still working on this?

**Comment by Sartoric** [comment]
> It's marked as draft

Oh, it wasn't intentional.

> are you still working on this?

No, I'm done

**Comment by balloob** [comment]
This PR is showing issues that are caught by `pre-commit`. Pre-commit should run automatically when making a commit to fix files.

**Comment by balloob** [comment]
@auanasgheps @Sartoric I fixed the file formatting, it should be good to go now.

When looking at the [intent dashboard](https://home-assistant.github.io/intents/), I noticed that Italian only needs `HassListAddItem` intent coverage to be considered usable. Would you be able to add this?

**Comment by balloob** [comment]
I have created a template generator to get LLMs to help with intent coverage in #2528. It created these files to kickstart Italian coverage of `HassListAddItem`: https://chatgpt.com/share/6734314d-3360-8002-a121-dbd2e80e4e10

**Comment by auanasgheps** [comment]
Thanks @balloob, I'll look into your suggestion and verify it!

**Comment by Sartoric** [comment]
@auanasgheps 
I can work on it if you need help

**Comment by Sartoric** [comment]
I'm trying to add the HassListAddItem
but the test return 
`AssertionError: Recognition failed for 'aggiungi mele alla mia lista trader joes'`

It should be a correct case, so I'm probably missing something stupid here :) 
Could it be due to something else ?

**Comment by auanasgheps** [comment]
Approving this one too. Thanks for your work.

**Pull request merged**
