### PR TITLE
[IT] Add Cover Synonyms

### PR DESCRIPTION
**Pull request by alessandroias**
Add `saracinesca` and `cler` as synonyms for `garage door`.
`cler` is used a lot in northern Italy.

### CODE REVIEW

**Comment by xraver** [comment]
I don't understand why it does not pass CI....

**Review by xraver — COMMENTED** [review]
what does it means "cler"?

**Comment by alessandroias** [comment]
It means "shutter"... I'm afraid it's a dialectal form, but it's so used here (in Milan) that it confused me.

**Comment by auanasgheps** [comment]
Looks like another language (bulgarian) is blocking the test.
Please wait until it is resolved before merging.

`Cler` is not Italian, we're not allowing dialects, otherwise the Italian files would be long like an encyclopedia...

**Comment by xraver** [comment]
> Looks like another language (bulgarian) is blocking the test. Please wait until it is resolved before merging.
> 
> `Cler` is not Italian, we're not allowing dialects, otherwise the Italian files would be long like an encyclopedia...

I agree.
thanks

**Comment by alessandroias** [comment]
As soon as I'm at home :)

**Pull request merged**
