### PR TITLE
[fr] add desk multi area

### PR DESCRIPTION
**Pull request by haade-administrator**
add desk area to light intents [fr]

### CODE REVIEW

**Review by flexy2dd — APPROVED** [review]

**Review by benjaminlecouteux — APPROVED** [review]

**Comment by haade-administrator** [comment]
[fr] add toilette, wc, buanderie, cellier, garage, cave area

**Comment by flexy2dd** [comment]
The script/test not work 
sentence "Allume la lumière du toilette" and "éteint la lumière du toilette" are not recognised

**Comment by piitaya** [comment]
Test are here to test the sentences, not to describe all the cases. I don't think we need this PR.

**Comment by flexy2dd** [comment]
> Tests are here to test the sentences, not to describe all the cases. I don't think we need this PR.
I agree with this, for me it's not necessary either, because it does not provide any functionality

**Comment by flexy2dd** [comment]
in line with  @piitaya  comment, PR not necessary in the context of testing

**Pull request closed without merging**
