### PR TITLE
Fix run test for sentences with list of slot name

### PR DESCRIPTION
**Pull request by witold-gren**
If we run this test in current configuration it will broke, because variable `lampę nocną` is written in lowercase and it will be not found in list of name in slots, because all name start capital letter.
```
  - sentences:
      - Zapal lampę nocną
      - Włącz lampę nocną
      - Zaświeć lampę nocną
    intent:
      name: HassTurnOn
      slots:
        name:
          - Lampę nocną
          - Lampka nocna
          - Lampkę nocną
          - Lampki nocnej
    response: Włączono lampę nocną
```

### CODE REVIEW

**Comment by witold-gren** [comment]
Hey @synesthesiam, could you check it? I found a bug with tests execution 😀

**Comment by dontinelli** [comment]
cf. #952

> Hey @synesthesiam, could you check it? I found a bug with tests execution grinning

Already in development: #952

**Comment by witold-gren** [comment]
Thank's for information. If my PR is redundant, it can simply be removed.

**Comment by schizza** [comment]
> Thank's for information. If my PR is redundant, it can simply be removed.

Closing.

**Pull request closed without merging**
