### PR TITLE
[el] HassGetState sentences/responses/tests for binary_sensor

### PR DESCRIPTION
**Pull request by chatziko**
HassGetState for binary_sensor was completely missing for greek. This PR adds all related translations: responses, sentences and tests (quite a lot of stuff). It brings it on par with the english version.

I tried to stay as close as possible to the english content, but also deal with the tricky aspects of greek. The test sentences are reasonably natural, IMHO.

### CODE REVIEW

**Comment by chatziko** [comment]
Just noticed that coincidentally there are two overlapping PRs submitted just hours ago! 
- #1369: contains responses for HassGetState
- #1370: contains state names for binary_sensors and a few more.

(murphy's law, I've been working for some time on this PR and the first greek PRs come just now :smile: )

Not sure what's the best way to proceed. Maybe merge this PR first which is much larger and will most certainly break, and then cherry-pick the changes from #1370 that are not included in mine? I'm willing to help with this if you want.

**Comment by dsimop** [comment]
Hello @chatziko, please have a look in the [Checks](https://github.com/home-assistant/intents/pull/1371/checks) and submit a 'fix'-commit if possible.
It is a general guideline that you commit small changes in order to avoid also these PR-overlapping conflicts.

**Comment by chatziko** [comment]
Hi @dsimop , I think I fixed the issues (`script/test` and `script/lint` pass on my local machine).

> It is a general guideline that you commit small changes in order to avoid also these PR-overlapping conflicts.

Agreed, I just viewed all binary_sensor intents as a single change, otherwise I'd need to open 20 tiny PRs (one for each device_class) which didn't seem very productive.

**Review by dsimop — APPROVED** [review]

**Comment by chatziko** [comment]
Thanks for merging the first 3 PRs, I rebased the long one on top of the new main and solved the conflicts.

**Comment by dsimop** [comment]
Thank you for your contribution @chatziko

**Comment by chatziko** [comment]
el is [green](https://home-assistant.github.io/intents/) again :smile: 

Thanks for merging!

**Pull request merged**
