### PR TITLE
Add Polish response, sentences and tests

### PR DESCRIPTION
**Pull request by rrakso**
```sh
(venv) $ python3 -m script.intentfest validate
All good!
(venv) $ pytest tests --language pl
============================================================================================================== test session starts ==============================================================================================================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/oskar/
collected 2 items                                                                                                                                                                                                                               

tests/test_language_intents.py .                                                                                                                                                                                                          [ 50%]
tests/test_language_sentences.py .                                                                                                                                                                                                        [100%]

=============================================================================================================== 2 passed in 0.37s ===============================================================================================================
```

### CODE REVIEW

**Comment by adorobis** [comment]
Great to see some initial contribution to Polish :) I believe some sentences should be reviewed though, what would be the best way to collaborate on them? Maybe a discord channel to have a few more eyes checking for the best sentence before submitting a PR?

**Comment by thecode** [comment]
> Great to see some initial contribution to Polish :) I believe some sentences should be reviewed though, what would be the best way to collaborate on them? Maybe a discord channel to have a few more eyes checking for the best sentence before submitting a PR?

The best way is to review the PR and add comments, you can suggest changes on the PR itself.

**Comment by balloob** [comment]
@adorobis I would also say that the more sentences the better. Anything that anyone could ever use to give a certain command should be listed/matched.

**Review by adorobis — COMMENTED** [review]
In `common.yaml' I would correct Polish sentences to:
`no_area: "Brak obszaru nazwanego {{ area }}"` - Polish name for Area in HA is "obszar"
`no_domain: "{{ area }} nie zawiara {{ domain }}"` - Area cannot own anything :)
`no_device_class: "{{ area }} nie zawiera {{ device_class }}" - as above. Alternatively could be "W {{ area }} nie ma {{ device_class }}"
Otherwise great work!

**Comment by adorobis** [comment]
@balloob - fully agree, especially for commands. But I believe for HA responses we are rather giving the one way - and it should be grammatically correct and reflect the naming that we use in HA - do I get it right?

**Comment by rrakso** [comment]
> `no_domain: "{{ area }} nie zawiara {{ domain }}"` - Area cannot own anything :) 

@adorobis I think that "zawierać" doesn't mean owning something. Look:
image

I think that I can change:
> `no_device_class: "{{ area }} nie zawiera {{ device_class }}` - as above. Alternatively could be "W {{ area }} nie ma {{ device_class }}"
to:
`no_device_class: "W {{ area }} nie ma {{ device_class }}`

What do you think about it @adorobis ?

**Comment by adorobis** [comment]
"Nie zawiera" is exactly my proposal. Your original one was "nie posiada". So you got the point :)

**Comment by rrakso** [comment]
> "Nie zawiera" is exactly my proposal. Your original one was "nie posiada". So you got the point :)

Ahh! You are right!  Thanks! Stupid error, sorry..

**Comment by synesthesiam** [comment]
Thanks @rrakso and @adorobis!

**Pull request merged**
