### PR TITLE
Add french responses

### PR DESCRIPTION
**Pull request by piitaya**

### CODE REVIEW

**Comment by synesthesiam** [comment]
Thanks!

**Review by benjaminlecouteux — COMMENTED** [review]
I see a problem with the "de"; which could turn into "du" or "de la" depending on the piece.

**Comment by piitaya** [comment]
Yes, we have the same issue with device name too because every word in french has a gender 🥲

**Comment by benjaminlecouteux** [comment]
Wouldn't it be cleaner to delete this "de" and replace it with a stop list?

**Comment by piitaya** [comment]
Can you provide some examples? 😀

**Comment by benjaminlecouteux** [comment]
I was thinking of something like :
Luminosité de {{ slots.area }}
Luminosité {{ list.determinant[slots.area] }} {{ slots.area }}
with {{ list.determinant }} which contain {"de la", "du", "dans la"} selected according the gender of slots.area

**Comment by piitaya** [comment]
The problem is that `area` can be every word and there is no gender on Home Assistant entity and area 😔
I tested with Siri and I think they have the gender of every word... 😅

**Comment by benjaminlecouteux** [comment]
I think there is no choice to link gender with different words. Would it be possible to create an external dictionary linking each word to its gender? I don't see any other solution.

**Comment by benjaminlecouteux** [comment]
It should be possible to automate this with a dictionary such as https://fr.wiktionary.org/

**Pull request merged**
