### PR TITLE
[BG] Add HassGetState sentences for Bulgarian

### PR DESCRIPTION
**Pull request by hristo-atanasov**

### CODE REVIEW

**Comment by hristo-atanasov** [comment]
@synesthesiam Can you help me a little? Currently I get error 'Не, лявата завеса е off', which translated means 'No, left curtain is off' .. Can a curtain have `off` state? I gues it should be `closed` or `opened` or I'm wrong and I'm missing something?

**Comment by synesthesiam** [comment]
Can you try adding translated names to your states in `_fixtures.yaml`? Something like:

```yaml
  - name: "лявата завеса"
    id: "cover.curtain_left"
    area: "living_room"
    state:
      in: "отворена"
      out: "open"
    attributes:
      device_class: curtain

```

**Comment by hristo-atanasov** [comment]
> Can you try adding translated names to your states in `_fixtures.yaml`? Something like:
> 
> ```yaml
>   - name: "лявата завеса"
>     id: "cover.curtain_left"
>     area: "living_room"
>     state:
>       in: "отворена"
>       out: "open"
>     attributes:
>       device_class: curtain
> ```

Can we have multiple `in` values?

**Comment by synesthesiam** [comment]
Home Assistant doesn't have multiple translated names for a state, so we probably shouldn't add them here. It is possible to include multiple possible responses in the test:

```yaml
tests:
  - sentences:
      - "..."
    response:
      - "response 1"
      - "response 2"
```

**Comment by BossNeo** [comment]
How long that will stay …can I go in and fix it.is unserious from language leader to post PR that not work and to stay 5+ days . Can we post only PR that pass tests ? 
Can I go in and fix the issues, or to make new branch ?  I wait too much.

**Comment by schizza** [comment]
> How long that will stay …can I go in and fix it.is unserious from language leader to post PR that not work and to stay 5+ days . Can we post only PR that pass tests ?
> Can I go in and fix the issues, or to make new branch ? I wait too much.

You can fix this PR - checkout this PR branch a push changes.
Only PR that pass tests will be accepted.

**Comment by BossNeo** [comment]
Problem is not in sentences. One problem that I saw is you sent test sentences to ALL response where you must  have , yes or no answer and count  it …. Etc. 
But in test sentence you put different response.
 I check it that solve one problem I thing other problem continue to use same logic.

**Comment by hristo-atanasov** [comment]
> Problem is not in sentences. One problem that I saw is you sent test sentences to ALL response where you must have , yes or no answer and count it …. Etc. But in test sentence you put different response. I check it that solve one problem I thing other problem continue to use same logic. Letter hope to have time to Make this fix and will commit if it is no problem.



> How long that will stay …can I go in and fix it.is unserious from language leader to post PR that not work and to stay 5+ days . Can we post only PR that pass tests ? Can I go in and fix the issues, or to make new branch ? I wait too much.

Unless You start paying me, I don't allow you to put ANY deadlines. We all contribute here and we are also humans. The reason I delayed fixing my contribution can vary - from visiting hospitals, visiting other countries, having children, having too hard working days. What ever the reason is - it is not you, the one who can put decide what is the deadline for my contribution. If you want to translate - do it, as you see no one is stopping you. This is а contribution, not a competition.

**Comment by hristo-atanasov** [comment]
> Problem is not in sentences. One problem that I saw is you sent test sentences to ALL response where you must have , yes or no answer and count it …. Etc. But in test sentence you put different response. I check it that solve one problem I thing other problem continue to use same logic. Letter hope to have time to Make this fix and will commit if it is no problem.

The problem was hidden else where. There was a new version for the answers file. Problem solved!

**Pull request merged**
