### PR TITLE
[BG]Shopping list

### PR DESCRIPTION
**Pull request by rudizl**
First try to add BG shopping list to Assist

### CODE REVIEW

**Comment by rudizl** [comment]
Any help will be appreciated... :(

**Comment by tetele** [comment]
I've left a PR on your repo. The indentation was wrong and YAML is very sensitive to indentation

**Comment by rudizl** [comment]
> I've left a PR on your repo. The indentation was wrong and YAML is very sensitive to indentation

Thank you so much! Still can't pass all tests, but it's a step ahead :)

**Comment by tetele** [comment]
It doesn't pass tests because of matching, not because of syntax errors, which is a step ahead :D

You're welcome and keep up the good work!

**Comment by hristo-atanasov** [comment]
> > I've left a PR on your repo. The indentation was wrong and YAML is very sensitive to indentation
> 
> Thank you so much! Still can't pass all tests, but it's a step ahead :)



> > I've left a PR on your repo. The indentation was wrong and YAML is very sensitive to indentation
> 
> Thank you so much! Still can't pass all tests, but it's a step ahead :)

Can you,  please, connect to me in  facebook, so I can give you some advices and we can have a talk between each other?
Pleace, find me at:
https://www.facebook.com/hristo.t.atanasov
Connect to me and after we speak, we will resolve the issues you have. Thank You in advance!

**Review by hristo-atanasov — APPROVED** [review]
Good!

**Comment by kyutov** [comment]
Hey @hristo-atanasov , @rudizl , I see that this PR is open for quite a long time. What needs to be done in order to pass the checks? Can I help with something in order to move it forward?

**Comment by rudizl** [comment]
> Hey @hristo-atanasov , @rudizl , I see that this PR is open for quite a long time. What needs to be done in order to pass the checks? Can I help with something in order to move it forward?

If I only knew... :) Feel free to colaborate.

**Comment by kyutov** [comment]
> > Hey @hristo-atanasov , @rudizl , I see that this PR is open for quite a long time. What needs to be done in order to pass the checks? Can I help with something in order to move it forward?
> 
> If I only knew... :) Feel free to colaborate.

I have made some improvements to the tests and I have created a PR to your repo. I think that now the tests would cover all the available combinations of sentences. I hope hope that this will help to pass the checks.

**Comment by rudizl** [comment]
@kyutov - pls check your CLA signature.

**Comment by kyutov** [comment]
> @kyutov - pls check your CLA signature.

The error is caused by a wrong author details in the commit which I have made to your repo. I have amended the author details as the bot suggested and I have created a new PR to your repo.

**Review by rudizl — COMMENTED** [review]
ok

**Comment by kyutov** [comment]
@rudizl , I see that the bot is still complaining about the author of my commit. I have delated the entire commit, so now the problem should be solved. I see that the problematic commit had disappeared from your repo as well. I think that now the bot will be happy so lets retry and we will see. If you prefer, you can rebase your repo before my commit and I will a new PR. Sorry for the mess 🤪

**Comment by rudizl** [comment]
> @rudizl , I see that the bot is still complaining about the author of my commit. I have delated the entire commit, so now the problem should be solved. I see that the problematic commit had disappeared from your repo as well. I think that now the bot will be happy so lets retry and we will see. If you prefer, you can rebase your repo before my commit and I will a new PR. Sorry for the mess 🤪

I give up...

**Pull request closed without merging**
