### PR TITLE
[DE] Add more variants to (un)locking

### PR DESCRIPTION
**Pull request by steffenrapp**

### CODE REVIEW

**Comment by steffenrapp** [comment]
Hope there are no conflicts with #1250

**Comment by mib1185** [comment]
this PR should be rebased, after #1250 is merged

**Review by mib1185 — CHANGES_REQUESTED** [review]
this PR should be rebased, after #1250 is merged

**Comment by mib1185** [comment]
I would further again highly recommend to read the [docs here](https://github.com/home-assistant/intents/blob/main/docs/README.md) how to contribute.
The [Edit on Github](https://github.com/home-assistant/intents/blob/main/docs/github/README.md) approach is suggested only for small changes in one file! Else it is highly recommended to use the [Local fork](https://github.com/home-assistant/intents/blob/main/docs/forking/README.md) or [Codespace](https://github.com/home-assistant/intents/blob/main/docs/codespace/README.md) approach 😉

**Review by mib1185 — APPROVED** [review]

**Pull request merged**
