### PR TITLE
[BG] Add HassGetDate and HassGetTime

### PR DESCRIPTION
**Pull request by kyutov**
Initial attempt to add HassGetDate and HassGetTime

## Summary by CodeRabbit

- **New Features**
	- Introduced support for Bulgarian language responses for the intents `HassGetCurrentDate` and `HassGetCurrentTime`.
	- Added response templates that dynamically format the current date and time in Bulgarian.
	- Included various sentence structures to recognize user queries for both date and time.

- **Tests**
	- Added test cases to ensure the functionality of the new intents `HassGetCurrentDate` and `HassGetCurrentTime`.

### CODE REVIEW

**Comment by hristo-atanasov** [comment]
I'm waiting for the poll in the bulgarian community of Home Assistant, in facebook, to decide if this variant of translation is good enought, because my opinion is different. If we let this asside, codderabbitai  offered a good handfull of additional changes, that will improve the translation. I suggest, that the translator will change his contribution and incloode the coderabbitai suggestions. I can also make the changes by myself if the author does not want to make them. Currently my answer for this commit is "No". I'll keep you in informed for my descision. For everyone that is reading this, the dilemma is which is the more correct way of naming the numbers (take 13, lets say) "тринадесет" or "тринайсет". Untill  few years the only official way for naming  the number 13 was "тринадесет". Now it was accepted to be named "тринайсет" also, but the second one comes from colloquial language. I will keep you posted.

**Comment by kyutov** [comment]
@hristo-atanasov , I agree with the changes which you have made 👍

Since you have added the following sentence:

+         - "[кажи ми] кой ден сме [днес]"

I have extended the response by adding the weekday in it. In that way we will provide more precise answer to the above sentence.

**Comment by hristo-atanasov** [comment]
> @hristo-atanasov , I agree with the changes which you have made 👍
> 
> Since you have added the following sentence:
> 
> * ```
>       - "[кажи ми] кой ден сме [днес]"
>   ```
> 
> I have extended the response by adding the weekday in it. In that way we will provide more precise answer to the above sentence.

Nice! I Even think that when asking "[кажи ми] кой ден сме [днес]", people will be more interested in the week day first, and the date will be an additional clarification. What do you think about a response in the other way - "вторник, седемнадесети Септември 2013-та"?

**Comment by hristo-atanasov** [comment]
Also I have one more question.
```
{% set hour_str = '{0:02d}'.format(slots.time.hour) %}
{% set minute_str = '{0:02d}'.format(slots.time.minute) %}
{{ hour_str }} часа и {{ minute_str }} минути
```
This template wi produce a time string like this: "01 часа и 02 минути"
I'm not shure how other TTS platforms will say it in bulgarian, but Google TTS will say it this way: "нула едно часа и нула две минути" ("zero one hours and zero 2 minutes").
So my questions is woudn't it be better if the hour is not zero padded, like "1 часа и 02 минути" ("едно часа и нула две минути") better? And do know a way if we can make it say "един" instead of "едно". I'll have to ask in the chat if there is a way to translate the names of the numbers for the hours and minutes too ..

**Comment by kyutov** [comment]
> > @hristo-atanasov , I agree with the changes which you have made 👍
> > Since you have added the following sentence:
> > 
> > * ```
> >       - "[кажи ми] кой ден сме [днес]"
> >   ```
> > 
> > I have extended the response by adding the weekday in it. In that way we will provide more precise answer to the above sentence.
> 
> Nice! I Even think that when asking "[кажи ми] кой ден сме [днес]", people will be more interested in the week day first, and the date will be an additional clarification. What do you think about a response in the other way - "вторник, седемнадесети Септември 2013-та"?

Yep, I agree that this sounds even better. I have changed the response in that way.

> Also I have one more question.
> 
> ```
> {% set hour_str = '{0:02d}'.format(slots.time.hour) %}
> {% set minute_str = '{0:02d}'.format(slots.time.minute) %}
> {{ hour_str }} часа и {{ minute_str }} минути
> ```
> 
> This template wi produce a time string like this: "01 часа и 02 минути" I'm not shure how other TTS platforms will say it in bulgarian, but Google TTS will say it this way: "нула едно часа и нула две минути" ("zero one hours and zero 2 minutes"). So my questions is woudn't it be better if the hour is not zero padded, like "1 часа и 02 минути" ("едно часа и нула две минути")?
> 
> Edit: I know I can translate it, but I'm not sure if it is ok to do it, because if some don't use TTS will see just a text "един часа и две минути" ("one a clock and two minutes") instead of "1 часа и 2 минути" or "01 часа и 02 минути". What do you think about this approach? Would it be a better solution?

During my tests I was using Azure TTS and it pronounces the string as expected - "един часа и две минути". I thought that all other TTS services will have the same comportment, but obviously they doesn't 🙂

I have made one change, which I hope will work with all the TTS services. Please test it with Google TTS.

**Comment by hristo-atanasov** [comment]
@kyutov Don't worry, I found it by luck. As I have Azure TTS setup already, but it is disabled and I'm currently using Google TTS. I'm communicating with Mike Hansen about this and already sent him a script that transforms years to bulgarian. He also found that he has access to a library, that can generate the same. So in the end we decided, that I'll wait until he interates this library and will write me to acknoleadge me when it is ready.

**Pull request merged**
