### PR TITLE
[DE] Add a few more variations to shopping list add item

### PR DESCRIPTION
**Pull request by ctron**
While one can argue if it's grammatically correct, it's in use.

### CODE REVIEW

**Review by mib1185 — CHANGES_REQUESTED** [review]
Hi @ctron could you please also add some additional test sentences to cover these additions?

**Comment by ctron** [comment]
> Hi @ctron could you please also add some additional test sentences to cover these additions?

Sure, done that. And rebased.

**Review by mib1185 — APPROVED** [review]
Thanks @ctron 👍

**Review by mib1185 — CHANGES_REQUESTED** [review]
Hi @ctron 
sorry, did not recognize that there are two different intents `HassShoppingListAddItem` and `HassListAddItem`. You should add these additions to both sentence files (_`shopping_list_HassShoppingListAddItem.yaml` and `todo_HassListAddItem.yaml`_) and also extend the tests for both.

**Comment by ctron** [comment]
> sorry, did not recognize that there are two different intents `HassShoppingListAddItem` and `HassListAddItem`.

Me neither :grinning: … thanks for pointing that out. I think I fixed it.

**Review by mib1185 — APPROVED** [review]
Thanks @ctron 👍

**Pull request merged**
