### PR TITLE
add shopping_list

### PR DESCRIPTION
**Pull request by panpawelgit**

### CODE REVIEW

**Comment by Uriziel01** [comment]
Hmm LGTM, could you please sign the CLA so I can approve it @panpawelgit? Thank you 😄

**Comment by panpawelgit** [comment]
> Hmm LGTM, could you please sign the CLA so I can approve it @panpawelgit? Thank you 😄

done

**Comment by Uriziel01** [comment]
Please add missing tests for the shopping list

**Comment by Uriziel01** [comment]
You've forgotten to declare the `shopping_list_item` itself in `_common.yaml`
please have a look at https://github.com/home-assistant/intents/blob/c2385003e61e0214b87affe6b1a9e8a0fff6a457/sentences/en/_common.yaml for reference

**Comment by grzech1983** [comment]
@panpawelgit I'm wondering have you tested this sentence on latest HA (I didn't tested it few versions back) ? I'm running 2023.8.3 and whatever I provide in dev tools Assist section I'm getting error "No intent matched".

**Comment by Uriziel01** [comment]
Yeah, as I've said the:
```
  shopping_list_item:
    wildcard: true
```
is missing, it seems it got merged without it. I'll fix it.

**Comment by Uriziel01** [comment]
NVM I've opened the portuguese directory by accident 😄 I'll look into it

**Comment by Uriziel01** [comment]
@panpawelgit Just checked it in a workspace again everything is still working fine, it's just the fact this was added after the release  (02.08 vs 03.08) so it did not made the cut, don't worry.

**Comment by grzech1983** [comment]
Ok. Thanks. I'll just wait then.

**Comment by fejrr** [comment]
New version and it still doesn't work.

**Comment by grzech1983** [comment]
Here you have text conversation with HA Assist. First one is in English:

image

and second one is in Polish:

image

as you can see in English it worked without any issues but in Polish it didn't worked.

```
Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
```

**Comment by fejrr** [comment]
Yes, that is my point. This translation was merged more on Aug 3 and it still doesn't work

**Comment by grzech1983** [comment]
I just wanted to post confirmation for @Uriziel01 to show him how it looks from withing HA GUI Assist conversation and provide version details.

**Comment by tetele** [comment]
The last embedded version of the intents repo in HA is from Aug 2nd https://github.com/home-assistant/core/blob/98ff3e233db3bac5b4d2c815cbe6bde13b57e4c6/requirements_all.txt#L1001

**Comment by Uriziel01** [comment]
Yes, I'll have a look into this, thank you 😄

**Comment by grzech1983** [comment]
It looks like intents has been updated in 2023.9.3

https://github.com/home-assistant/core/blob/dev/requirements_all.txt

**Comment by Uriziel01** [comment]
Yup, confirmed, everything is working as intended now.

**Comment by fejrr** [comment]
Good thing I asked on discord because they missed it
obraz

**Pull request merged**
