### PR TITLE
[GL] Add galician language

### PR DESCRIPTION
**Pull request by cibernox**
I'm adding Galician as a new language. Since it's a new language that implicitly means i'm implicitly applying as Language Leader, at least for now.

I used the Spanish definitions as a starting point and adapted them.

### CODE REVIEW

**Comment by cibernox** [comment]
I’ll check the failings tests tonight. Consider this a WIP for the time being.

**Comment by synesthesiam** [comment]
Looks like one `bg` file is included in the PR by accident.

**Comment by cibernox** [comment]
@synesthesiam Fixed. Also I can appoint myself as leader if that's OK.

**Comment by cibernox** [comment]
I believe this is ready to be merged. Should I add myself as language leader in languages.yaml?

**Pull request merged**
