### PR TITLE
[zh-cn] Support for Chinese Simplified Language

### PR DESCRIPTION
**Pull request by al-one**
```bash
$ python3 -m script.intentfest parse --language zh-cn --sentence '打开左侧窗帘'
{
  "text": "打开左侧窗帘",
  "match": true,
  "intent": "HassTurnOn",
  "slots": {
    "name": "cover.curtain_left",
    "domain": "fan"
  }
}

$ python3 -m script.intentfest parse --language zh-cn --sentence '打开卧室的左侧窗帘'
{
  "text": "打开卧室的左侧窗帘",
  "match": true,
  "intent": "HassTurnOn",
  "slots": {
    "area": "bedroom",
    "name": "cover.curtain_left",
    "domain": "fan"
  }
}
```

- #416 
- #143 
- #698 
- https://developers.home-assistant.io/blog/2023/01/20/cover-intent-deprecated/

### CODE REVIEW

**Comment by al-one** [comment]
I resolved the conflicts and made a lot of modifications. Please review again.

```bash
$ python3 -m script.intentfest validate --language zh-cn
Language: zh-cn
All good!

$ pytest tests --language zh-cn
=== test session starts ====
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
rootdir: /workspaces/home-assistant-intents, configfile: pyproject.toml
collected 19 items                                                                                                                                                                                                                                                                                                  

tests/test_language_intents.py ..........                                                                                                                                                                                                                                                                     [ 52%]
tests/test_language_sentences.py .........                                                                                                                                                                                                                                                                    [100%]

=== 19 passed in 1.19s ====
```

**Comment by al-one** [comment]
I tested this language in Codespaces and executed `script/test`, all passed. Please approve the workflow again.

```bash
$ script/test

==== test session starts ====
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /workspaces/home-assistant-intents, configfile: pyproject.toml, testpaths: tests
collected 931 items 
...
===== 931 passed in 104.50s (0:01:44) =====
```

**Comment by schizza** [comment]
You have a mistake in your PR

```
=========================== short test summary info ============================
[1787](https://github.com/home-assistant/intents/actions/runs/4044143186/jobs/6953930451#step:8:1788)
FAILED tests/test_language_sentences.py::test_homeassistant_HassTurnOff[zh-cn] - AssertionError: Missing slot area for: 关闭卧室灯 (value=bedroom)
[1788](https://github.com/home-assistant/intents/actions/runs/4044143186/jobs/6953930451#step:8:1789)
assert None is not None
[1789](https://github.com/home-assistant/intents/actions/runs/4044143186/jobs/6953930451#step:8:1790)
================== 1 failed, 949 passed in 178.21s (0:02:58) ===================

```

then run `python3 -m script.intentfest validate --language zn-cn` and `pytest tests --language zn-cn`

**Comment by al-one** [comment]
Fixed now.

**Pull request merged**
