### PR TITLE
Update _common.yaml homeassistant*.yaml for Vietnamese Languages

### PR DESCRIPTION
**Pull request by dinhchinh82**
Added  the _common.yaml and homeassistant*.yaml for Vietnamese Languages

### CODE REVIEW

**Comment by synesthesiam** [comment]
@dinhchinh82 we need at least as many test sentences as there are templates :+1:

**Comment by dinhchinh82** [comment]
> @dinhchinh82 we need at least as many test sentences as there are templates 👍

@synesthesiam I just updated some test sentences. Please check.

**Comment by synesthesiam** [comment]
Very close @dinhchinh82! Just need tests for one file, and fix the language in another.

**Comment by dinhchinh82** [comment]
> Very close @dinhchinh82! Just need tests for one file, and fix the language in another.

@synesthesiam I just updated more test cases and fix the language id.

**Pull request merged**
