### PR TITLE
@edgein666 [SV] Added ändra as dimra and several tests

### PR DESCRIPTION
**Pull request by edgein666**

### CODE REVIEW

**Comment by edgein666** [comment]
It's obvious that I still don't understand how this works. :)

Do I need to create a new branch for every PR or why is my "added skip word" PR here as well.

I will see if I can find a good youtube or something to learn some more about git and github.

**Comment by schizza** [comment]
Yes, for every new work, you have to add a new branch to your fork. Do some work, push changes to your main fork and request PR to upstream/main (main of homeassistatn/intents)

**Comment by schizza** [comment]
@edgein666 And before you start new branch, make sure you update your main from upstream/main.

**Comment by edgein666** [comment]
thanks @schizza!

**Comment by edgein666** [comment]
ping @larsdunemark and @Robin-St 

what do you think about my change, should I create a new PR in a new branch or can we handle it here?

**Comment by Robin-St** [comment]
> 
I think it looks OK. The potential problem is with many people simultaneously working on the same/similar sections of code the risk of merge conflicts increases but its quite calm here now :)

**Review by larsdunemark — APPROVED** [review]
Looks good to me, did a rebase on latest main to remove the merged commit of "skip_words"

**Pull request merged**
