### PR TITLE
[pt-BR] Sentences, responses and tests

### PR DESCRIPTION
**Pull request by dclobato**
- Change name to pt-BR, to be similar to fr-CA, de-CH
- Remove terms presents on _common.yaml and _fixture.yaml that only make sense on pt-PT
- Start sentences/tests/responses from scratch, instead of translating sentences from english/spanish
- Add file for sentences from scene, script and lock domains

### CODE REVIEW

**Comment by dclobato** [comment]
@synesthesiam, just did changes requested on previous PR

**Comment by dclobato** [comment]
@synesthesiam I don't get what's is going on...

I changed the language code to pt-BR (same idea of fr-CA, e.g.).  Removed the the old language files (using git), and added the new ones using the script for generating new language.

Files that already exists on the previous version are still on the "pt-br" dir, despite the folder name on the file system is pt-BR.  That's why lint is complaining...

What should I change here to fix this?

**Comment by dclobato** [comment]
If some one want to solve this case-sense problem, be my guest and take ownership of this PR.  I give up.

**Comment by synesthesiam** [comment]
I'm sorry, I haven't had a chance to look into this just yet 🫤

**Comment by nikito7** [comment]
repo is archived

**Pull request closed without merging**
