### PR TITLE
[DE] Add intent for removing items from shopping list

### PR DESCRIPTION
**Pull request by Lesekater**
Added a intent to add items to shopping lists.

## Summary by CodeRabbit

- **New Features**
  - Introduced a new intent for removing items from a shopping list, enhancing user interaction.
  - Added personalized response templates in German to confirm item removal.
  - Included various sentence structures in German to support user requests for item removal.

- **Tests**
  - Implemented test cases to ensure accurate recognition of removal requests for specific items.

### CODE REVIEW

**Comment by Lesekater** [comment]
Started draft for core repo:
https://github.com/home-assistant/core/pull/126786

**Comment by mib1185** [comment]
> Started draft for core repo: [home-assistant/core#126786](https://github.com/home-assistant/core/pull/126786)

I think we should first have the core PR merged, before adding intents, therefore I'm setting this PR here to draft mode, as long as the core PR is not merged.

**Review by mib1185 — CHANGES_REQUESTED** [review]
besides waiting for the core PR, I've already some review comments on this one.

btw. the title and description needs to be adjusted, since you're adding the remove itents, not the add intents 😉

**Comment by frenck** [comment]
FYI @Lesekater @mib1185 The linked core PR has been closed.

../Frenck

**Comment by Lesekater** [comment]
> FYI @Lesekater @mib1185 The linked core PR has been closed.
> 
> ../Frenck

Thx for mentioning it. 

Yes, i closed it, after working on a similar PR for the todo component, where allenporter mentioned, that it would probably be better to focus on the mark item as completed intent rather than the more destructive remove item itent (https://github.com/home-assistant/core/pull/127046#issuecomment-2395592824). 

I opened another core PR for marking items as complete on the shopping list (https://github.com/home-assistant/core/pull/128565). I could probably create a new PR here too if the core PR goes through, but I think most of the wording can stay the same between *item completion* and *item removal*.

**Comment by mib1185** [comment]
I would vote for closing this one here, since it was designed and targeted to another approach.
Further, please wait with opening a new PR here, as long as the core PR (https://github.com/home-assistant/core/pull/128565) is not accepted and merged - this is to avoid unnecessary efforts on your side and also on the reviewers side.

**Pull request closed without merging**
