### PR TITLE
[DE] Add new variations to lock_HassGetState

### PR DESCRIPTION
**Pull request by steffenrapp**
As #1243 seems to be not active anymore I created a new PR with some more phrases added.

### CODE REVIEW

**Comment by mib1185** [comment]
Hi @steffenrapp 
tbh, I would like to finish #1243, afterwards the leftover changes from your PR can be reviewed/merged

**Comment by steffenrapp** [comment]
@mib1185 agree, as there was no activity for 3 weeks now I decided to open up a new PR.

**Comment by mib1185** [comment]
in case you have an idea for improvement and find an (_obviously stale_) open PR, than please comment it.
I'll try to react on this, if i do not, than just ping me on it 😉

**Comment by mib1185** [comment]
#1243 is merged, please resolve the conflicts now

**Comment by steffenrapp** [comment]
Should be fine now. Thank you @mib1185 for the fast reaction 👍

**Review by mib1185 — APPROVED** [review]
LGTM, thx @steffenrapp 👍

**Pull request merged**
