### PR TITLE
[pt-BR] Adding on/off lights sentences

### PR DESCRIPTION
**Pull request by leozanotto**
- Improving tests/_fixtures file
- Improving sentences/_common file
- Adding sentences to on/off lights domain
- Improving on/off responses

### CODE REVIEW

**Review by nikito7 — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by leozanotto** [comment]
> Resolve conflicts

Done!

**Review by nikito7 — APPROVED** [review]

**Review by nikito7 — APPROVED** [review]

**Comment by nikito7** [comment]
I can't merge changes for 'languages.yaml' 🤷‍♂️

**Review by nikito7 — APPROVED** [review]

**Comment by nikito7** [comment]
> > Resolve conflicts
> 
> Done!

Try again. Thank you

**Review by nikito7 — APPROVED** [review]

**Comment by nikito7** [comment]
pytest --language pt-br

**Comment by leozanotto** [comment]
Thanks @nikito7 fixing the linting
Right know I think I have fixed all expansion rules I have changed at their respective sentences (liga/desliga/name) to the new ones on __common

**Comment by nikito7** [comment]
> I saw you added some test sentences for TurnOn/Off and there are some warnings, maybe I should add a light entity at sala_de_estar to get some coverage?

Try do this first

**Comment by nikito7** [comment]
Done

**Pull request merged**
