### PR TITLE
Clean up some spaces and adding test

### PR DESCRIPTION
**Pull request by larsdunemark**

### CODE REVIEW

**Comment by larsdunemark** [comment]
@edgein666 @Robin-St  do you have any input on this?

**Comment by Robin-St** [comment]
> @edgein666 @Robin-St do you have any input on this?

Looks good

**Comment by edgein666** [comment]
> @edgein666 @Robin-St  do you have any input on this?

Looks good, just had one question which I made a comment about in the file.

**Comment by larsdunemark** [comment]
> > @edgein666 @Robin-St  do you have any input on this?
> 
> Looks good, just had one question which I made a comment about in the file.

I don't see any comment in the file, was it submitted in the comment or lost some how?

**Comment by edgein666** [comment]
Comment was maybe wrong word. It says that I started a "review"?

**Comment by larsdunemark** [comment]
> Comment was maybe wrong word. It says that I started a "review"?

okej, in that case I think that you can just submit the review, it will be a comment but inline with the file view also for line comments.

**Comment by edgein666** [comment]
Got it! Please go ahead.

**Pull request merged**
