### PR TITLE
[PT-BR] New sentences and some non-translated are now translated

### PR DESCRIPTION
**Pull request by jmceara**
As requested by @tetele in https://github.com/home-assistant/intents/discussions/1768#discussioncomment-7830669

based on https://github.com/home-assistant/intents/pull/1767

waiting for: https://github.com/home-assistant/core/pull/105524

### CODE REVIEW

**Comment by HepoH3** [comment]
I've resolved merge conflict happened after merging main branch into this one. Hope it's okay.

**Comment by tetele** [comment]
This ia a very dirty PR. Can we clean it up @jmceara ?

**Comment by jmceara** [comment]
> This ia a very dirty PR. Can we clean it up @jmceara ?

Of course! What you need me to do?

**Comment by tetele** [comment]
Remove all commits which aren't yours, leave in only `pt-br` changes, then rebase against the base branch. Alternatively, close it and start another with only your changes

**Comment by jmceara** [comment]
Ok, sorry for new.....new here with PR. Will do right now.

**Comment by tetele** [comment]
New PR: #1798

**Pull request closed without merging**
