### PR TITLE
Add tests to support PR#1986

### PR DESCRIPTION
**Pull request by OzGav**
https://github.com/home-assistant/intents/pull/1986

### CODE REVIEW

**Comment by tetele** [comment]
This won't work, as the CI pipeline needs tests to pass **per PR** so you have to commit your tests to #1986

**Comment by v1k70rk4** [comment]
Oops :) Sorry for the many requests, but this is not right. The essence of PRs is that you submit them and after approval, the system runs a test on them. Now, #1986 will not run either, because there is no test in that PR, and this one does not have a sentence to test. It would be wise to close #1987 and add it to #1986. If that doesn't work, close both and put everything together in a third one :)

But it's also possible that @tetele is a guru and will solve it :) But the correct procedure is definitely the above method, where a PR must be valid on its own.

**Comment by v1k70rk4** [comment]
Well, that was faster :D

**Comment by tetele** [comment]
> Now, #1986 will not run either, because there is no test in that PR, and this one does not have a sentence to test.

It would run, but being @OzGav 's first contribution, a maintainer has to approve the CI workflow. Which I will as soon as he commits the missing tests.

**Pull request closed without merging**
