### PR TITLE
[UR] adding Hass Get state

### PR DESCRIPTION
**Pull request by AalianKhan**

### CODE REVIEW

**Comment by AalianKhan** [comment]
Hello @synesthesiam
I am getting an Assertion error but I am stumped on this one.
image
I tried to condense the recognition as much as possible but it still doesn't go through
`"{name} کیا ہے"`

**Comment by synesthesiam** [comment]
@AalianKhan You need to add a new entity to your fixtures, like:

```yaml
entities:
  - name: Outside Temperature
    id: sensor.outside_temperature
    area: garage
    state: "42"
    attributes:
      unit_of_measurement: "°F"
```

**Comment by AalianKhan** [comment]
Thanks @synesthesiam! that worked
Since our scripture is right to left, our question mark is reversed `؟`, testing fails if I use this. However, it passes if I use `?`

**Comment by synesthesiam** [comment]
I will add "؟" to the list of punctuation for the next version.

**Pull request merged**
