### PR TITLE
[RU] Change word endings depending on numeric state in HassClimateSetTemperature

### PR DESCRIPTION
**Pull request by SenMorgan**

### CODE REVIEW

**Comment by HepoH3** [comment]
Hi!
There is some thing you should know. In this repo I can can merge pull requests only via "squash and merge" way.
It means that after merge, this repo will have single commit contains all of commits from your PR. That means also that this repo will have different commit history than you have in your fork.

So after your PR merged in main repo, you should sync your fork by discarding your commits in fork repo, and pulling merged commit, that contains all of your discarded commit changes.

Right now if you look at the PR commits, you'll see a lot of commits that we already merged, it potentially will cause a merge conflict (right now it's not the problem). But it's difficult to track what's new here and what's already done (especially if you changed something in code that we changed yesterday).

**Comment by HepoH3** [comment]
> Hi! There is some thing you should know. In this repo I can can merge pull requests only via "squash and merge" way. It means that after merge, this repo will have single commit contains all of commits from your PR. That means also that this repo will have different commit history than you have in your fork.
> 
> So after your PR merged in main repo, you should sync your fork by discarding your commits in fork repo, and pulling merged commit, that contains all of your discarded commit changes.
> 
> Right now if you look at the PR commits, you'll see a lot of commits that we already merged, it potentially will cause a merge conflict (right now it's not the problem). But it's difficult to track what's new here and what's already done (especially if you changed something in code that we changed yesterday).

Oh, actually I can track new stuff, because old commit did not change anything in the main branch, quite interesting but okay.

**Review by HepoH3 — APPROVED** [review]

**Comment by HepoH3** [comment]
Thanks again!

**Comment by SenMorgan** [comment]
Ok, thank you for detailed information. This is my first time creating pull requests in such a project, so may be I disunderstood something. The right flow for adding a feature will be like that:

Fork repo → create branch → make changes → commit and PR → after successful PR i should discard my changes and my branch by syncing with main branch → then create NEW branch → make changes and so the same stuff again.

Is that right?

**Comment by SenMorgan** [comment]
And should I press this «Delete branch» button on GitHub merge page when PR is merged?
image

**Comment by HepoH3** [comment]
Yeah, something like this.

Actually, you're not forced to create individual branches for single PR, you can work just in main branch. There is no differences for PR from which branch changes will go.

But if happened that you'll work on two different features (e.g. if you were work on `homeassistantGetState` and `coverTurnOff`) you should make this changes in isolated environment (means work on separate branches) so your changes will not interfere.

In that case, yeah, after PR merged and if you have no plans on continue working on `coverTurnOff` you can just delete this branch and create another if you happen to work on two features in parallel again.

**Comment by SenMorgan** [comment]
Got it, thanks again

**Pull request merged**
