### PR TITLE
Add more media player service calls

### PR DESCRIPTION
**Pull request by OzGav**

### CODE REVIEW

**Comment by tetele** [comment]
As discussed on Discord, this PR is rather large. I'd advise you to break it up into smaller PRs, one for each new intent or pair of intents (such as Mute/Unmute). In order to prevent merge conflicts between the PRs, you can opt to use [local lists](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax#local-lists).

**Comment by frenck** [comment]
@tetele The split you've requested seem to have happened. Could you take another look?

@OzGav Meanwhile, a merge conflict has occurred as well. Could you take a look and resolve that?

Thanks! 👍 

../Frenck

**Comment by tetele** [comment]
IIRC, @synesthesiam said that these intents would not make the core, as they are too specific for MA. If so, let's close this PR for now.

But if I am mistaking, let me know and I can take another look. Either way, being new functionality (albeit in English), I'd like Mike to have the final say.

**Comment by OzGav** [comment]
Yes I understand we are just running with this one https://github.com/home-assistant/intents/pull/2080 That one has merge conflicts so maybe Frenck meant that one?

**Pull request closed without merging**
