### PR TITLE
Remove area "all" slot for all languages

### PR DESCRIPTION
**Pull request by piitaya**
Following https://github.com/home-assistant/intents/pull/1500
`area: all` doesn't target all areas but only the area called "all" so it should not be used.

### CODE REVIEW

**Review by TheFes — APPROVED** [review]
Fine for the NL intents

**Review by LaStrada — APPROVED** [review]
NB is good as well

**Review by andrejs2 — APPROVED** [review]
Approved for `sl.` Thanks @piitaya.

**Comment by synesthesiam** [comment]
Thanks!

**Pull request merged**
