### PR TITLE
[EL] Update responses 

### PR DESCRIPTION
**Pull request by apo-mak**
[EL] Update responses to be onpar with EN

### CODE REVIEW

**Review by dsimop — CHANGES_REQUESTED** [review]
The pipeline checks have to be green. Please run the respective tests before commiting/creating a PR, in order to ensure your PR can be merged.

**Comment by apo-mak** [comment]
> The pipeline checks have to be green. Please run the respective tests before commiting/creating a PR, in order to ensure your PR can be merged.



> The pipeline checks have to be green. Please run the respective tests before commiting/creating a PR, in order to ensure your PR can be merged.

well i run the script and i get " All Good!"

``` bash
python -m script.intentfest validate --language el
Language: el
[WARN] tests\el\climate_HassClimateGetTemperature.yaml: 1 test(s) missing response check
[WARN] tests\el\climate_HassClimateSetTemperature.yaml: 1 test(s) missing response check
[WARN] tests\el\fan_HassTurnOff.yaml: 2 test(s) missing response check
[WARN] tests\el\fan_HassTurnOn.yaml: 2 test(s) missing response check
[WARN] tests\el\homeassistant_HassNevermind.yaml: 1 test(s) missing response check
[WARN] tests\el\homeassistant_HassTurnOff.yaml: 2 test(s) missing response check
[WARN] tests\el\homeassistant_HassTurnOn.yaml: 5 test(s) missing response check
[WARN] responses\el\HassGetState.yaml: unused response default
[WARN] responses\el\HassGetState.yaml: unused response where
[WARN] responses\el\HassTurnOff.yaml: unused response fans_area
[WARN] responses\el\HassTurnOff.yaml: unused response cover
[WARN] responses\el\HassTurnOff.yaml: unused response lock
[WARN] responses\el\HassTurnOn.yaml: unused response fans_area
[WARN] responses\el\HassTurnOn.yaml: unused response cover
[WARN] responses\el\HassTurnOn.yaml: unused response scene
[WARN] responses\el\HassTurnOn.yaml: unused response script
[WARN] responses\el\HassTurnOn.yaml: unused response lock

All good! 
```

**Comment by dsimop** [comment]
You can run the following command in order to ensure that everything is ok, before pushing: 
`pytest tests --language el`

Specifically, the returned error response from the checks is the following:
`FAILED tests/test_language_sentences.py::test_climate_HassClimateGetTemperature[el] - AssertionError: Incorrect response for: Ποια είναι στο σαλόνι η θερμοκρασία
assert 'None βαθμοί' in {'22 βαθμοί'}`

Additionally, please remember to keep the following folders updated for every change:
-`responses`
-`sentences`
-`tests`

**Comment by apo-mak** [comment]
> You can run the following command in order to ensure that everything is ok, before pushing: `pytest tests --language el`
> 
> Specifically, the returned error response from the checks is the following: `FAILED tests/test_language_sentences.py::test_climate_HassClimateGetTemperature[el] - AssertionError: Incorrect response for: Ποια είναι στο σαλόνι η θερμοκρασία assert 'None βαθμοί' in {'22 βαθμοί'}`
> 
> Additionally, please remember to keep the following folders updated for every change: -`responses` -`sentences` -`tests`

i was about to create a diferent pull for the sentences  and tests.

i see that is  probably better to merge them here..

i will try the pytest tests --language el 
Thanx

**Review by dsimop — CHANGES_REQUESTED** [review]
As mentioned, the tests have to pass before committing/pushing in order the PR to be accepted. Try to run the respective `pytest` command. In case of  any further questions or clarifications, please do let me know.

**Comment by dsimop** [comment]
Just a quick suggestion for future Pull Requests: consider committing smaller PRs with a single intent rather than submitting one large PR that affects numerous intents. This approach helps streamline the review process and makes it easier to pinpoint changes.

Thank you for your time, your help, and of course your valuable contributions! 👍

**Comment by apo-mak** [comment]
> Just a quick suggestion for future Pull Requests: consider committing smaller PRs with a single intent rather than submitting one large PR that affects numerous intents. This approach helps streamline the review process and makes it easier to pinpoint changes.
> 
> Thank you for your time, your help, and of course your valuable contributions! 👍

Thank you for the suggestion, I was trying to make smaller ORs by group by folder. Not a good idea it seems.

I am trying to troubleshoot these errors,
I do not know if you also have a suggestion for them.
It will be much appreciated.


```
FAILED tests/test_language_intents.py::test_person_HassGetState[el] - AssertionError: Missing expansion rule: <where_is>. Are you missing an 'expansion_rules' entry in _common.yaml or in the intent data?
FAILED tests/test_language_intents.py::test_sensor_HassGetState[el] - AssertionError: Missing expansion rule: <what_is_the_class_of_name>. Are you missing an 'expansion_rules' entry in _common.yaml or in the intent data?

```

i had the same error on  validate.py   but i fixed by adding 
```
        content = yaml.safe_load(file_path.read_text(encoding="utf8"))
```

on line 338

**Comment by dsimop** [comment]
Hello @apo-mak, I see you have touched 18 files so far. They are a lot for such a PR. I would recommend to close it and start with multiple/smaller PRs, which will be focused only in discrete changes. For instance, a PR for the HassTurnOff, another one for the HassGetWeather and so on. In that way, the process will be better optimized and we will be able to review the PRs easier and faster. 

Unfortunately, I will not have the time this week in order to help you with solving the errors of the current PR.

**Comment by apo-mak** [comment]
> Hello @apo-mak, I see you have touched 18 files so far. They are a lot for such a PR. I would recommend to close it and start with multiple/smaller PRs, which will be focused only in discrete changes. For instance, a PR for the HassTurnOff, another one for the HassGetWeather and so on. In that way, the process will be better optimized and we will be able to review the PRs easier and faster.
> 
> Unfortunately, I will not have the time this week in order to help you with solving the errors of the current PR.

Ok, np, Let leave this as draft and I will use it to split it to multiple per type PR’s (3 files response,sentence,test per PR).
Have a nice week and when you have time I will appreciate some help, I want to make EL on par and if possible, better than EN before the next HA update 😊, you can find me in discord for faster communication.

**Comment by apo-mak** [comment]
I added as Draft the ones that have errors, and I was unable to find a solution.

**Pull request closed without merging**
