### PR TITLE
[DE] Extend on-off and up-down variations

### PR DESCRIPTION
**Pull request by mib1185**

### CODE REVIEW

**Comment by balloob** [comment]
@scorpoon can you take a look ?

**Comment by ChristophCaina** [comment]
hm... maybe also:

- "<schliessen> <area> (<abdeckung> | <tor> | <garage>)"
- "<schliessen> (<abdeckung> | <tor> | <garage>) <area>"

"schließe xyz auf" / "schließe xyz ab"

**Comment by mib1185** [comment]
HI @ChristophCaina 
aufschließen and abschließen are actions for locks, but not covers.

**Comment by ChristophCaina** [comment]
Hi, I agree - but usually, if you have an automated garage door, these are like covers - and my additional suggestion with using "schliesse ab" / "schliesse auf" was made due to the already available "schließe xyz"...
I think, it could be added as "optional word" to that sentence? (The garage door should also lock when it will be closed) ;)

**Comment by balloob** [comment]
@Scorpoon can you please review this PR.

**Comment by vwccvr6** [comment]
Seems that @Scorpoon isn't reachable anymore...

**Review by RosemaryOrchard — APPROVED** [review]

**Comment by easterapps** [comment]
Hi @mib1185, can you please resolve the open conflicts. I will then review it promptly so that it can be merged

**Review by easterapps — APPROVED** [review]

**Pull request merged**
