### PR TITLE
zh-hk language owner

### PR DESCRIPTION
**Pull request by swonge**
## Summary by CodeRabbit

- **New Features**
  - Added support for Chinese (Hong Kong) language.
  - Introduced a new language leader for Chinese (Hong Kong).

### CODE REVIEW

**Comment by swonge** [comment]
Please review this PR

**Comment by synesthesiam** [comment]
@swonge Are you interested in being the language leader for `zh-hk`?

**Comment by swonge** [comment]
Yes
    On Friday 7 June 2024 at 13:59:14 GMT-7, Michael Hansen ***@***.***> wrote:  
 
 


@swonge Are you interested in being the language leader for zh-hk?

**Comment by swonge** [comment]
> Yes On Friday 7 June 2024 at 13:59:14 GMT-7, Michael Hansen ***@***.***> wrote: @swonge Are you interested in being the language leader for zh-hk? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Yes, I am.

**Comment by synesthesiam** [comment]
OK, great! The process to become a language leader is to submit at least two small PR's for your language with translations. If everything looks good, I will add you as a leader in a separate PR.

I'm closing this PR for now; please message me when you have your two translation PR's ready. Thanks again :+1:

**Comment by swonge** [comment]
hi Synesthesiam,
Actually I did, I have couple of PR but no one response to those

1. update zh-hk translation for lock_hass, scene_hass, script_hass - [https://github.com/home-assistant/intents/pull/1853](url)
2. zh-hk translation - [https://github.com/home-assistant/intents/pull/1853](url)
3. zh-hk script_Hass - [https://github.com/home-assistant/intents/pull/1222](url)
4. zh-hk scene_Hass - [https://github.com/home-assistant/intents/pull/1219](url)
5. zh-hk - lock_Hass - [https://github.com/home-assistant/intents/pull/1217](url)

**Comment by swonge** [comment]
> OK, great! The process to become a language leader is to submit at least two small PR's for your language with translations. If everything looks good, I will add you as a leader in a separate PR.
> 
> I'm closing this PR for now; please message me when you have your two translation PR's ready. Thanks again 👍

hi Synesthesiam,
Thanks for your response
Actually I did, I have couple of PR but no one response to those

update zh-hk translation for lock_hass, scene_hass, script_hass - [https://github.com/home-assistant/intents/pull/1853](https://github.com/home-assistant/intents/pull/url)
zh-hk translation - [https://github.com/home-assistant/intents/pull/1853](https://github.com/home-assistant/intents/pull/url)
zh-hk script_Hass - [https://github.com/home-assistant/intents/pull/1222](https://github.com/home-assistant/intents/pull/url)
zh-hk scene_Hass - [https://github.com/home-assistant/intents/pull/1219](https://github.com/home-assistant/intents/pull/url)
zh-hk - lock_Hass - [https://github.com/home-assistant/intents/pull/1217](https://github.com/home-assistant/intents/pull/url)
if you look up "zh-hk" from pull request search, you should see my work, seem no one pay attention to my PRs

**Pull request closed without merging**
