### PR TITLE
Update light_HassTurnOn.yaml

### PR DESCRIPTION
**Pull request by jirimissbach**
adding plural, and singular variants as well as the formal vs spoken language

### CODE REVIEW

**Comment by balloob** [comment]
When adding sentences, you also need to update the corresponding test files. They live in the `tests` folder.

**Comment by jirimissbach** [comment]
Hi Paulus,
 I did update the test files; however, when I saw the failure, I realized that a sentence was missing (at least based on the error  - tests/cs/light_HassTurnOn.yaml: not all sentences have tests). 

I have tried to correct that now.  Sorry it's my 1st time on Github, but I'll do my best to be useful!

**Comment by TomaszPilch** [comment]
@jirimissbach I think you need create new PR from branch because this can't be merged, the tests will never pass without the test files. You should close these PRs.

**Comment by jirimissbach** [comment]
closing due to errors

**Pull request closed without merging**
