### PR TITLE
[SL] weather and person untraslated states fix

### PR DESCRIPTION
**Pull request by andrejs2**
pushed from weather-and-person-fixes-untraslated

### CODE REVIEW

**Review by tetele — CHANGES_REQUESTED** [review]
Please clean the PR and include only your modifications

**Comment by andrejs2** [comment]
> Please clean the PR and include only your modifications

I really don't know how to handle this. After I made changes to responses (`HassGetState.yaml`) I broke some other tests for person and weather. I did rebase with [branch](https://github.com/home-assistant/intents/tree/untranslated-state) but then it includes other commits....ahhh.

Is it ok to close this PR? I'll wait with PR (open new PR) till this is resolved and merged...

**Comment by tetele** [comment]
> Is it ok to close this PR? I'll wait with PR (open new PR) till this is resolved and merged...

That will probably be the easier thing to do. So... any PR that you create should only contain your updates. This is really important!

It's ok if you don't merge for now and me and/or @synesthesiam will try to do that when the functionality is ready.

Thanks!

**Comment by andrejs2** [comment]
> > Is it ok to close this PR? I'll wait with PR (open new PR) till this is resolved and merged...
> 
> That will probably be the easier thing to do. So... any PR that you create should only contain your updates. This is really important!
> 
> It's ok if you don't merge for now and me and/or @synesthesiam will try to do that when the functionality is ready.
> 
> Thanks!

@tetele Thanks!

**Pull request closed without merging**
