### PR TITLE
[de] Add area support for HassTurnOn / HassTurnOff intents

### PR DESCRIPTION
**Pull request by freeDom-**
Add area support for HassTurnOn / HassTurnOff intents

### CODE REVIEW

**Review by mib1185 — CHANGES_REQUESTED** [review]
Hi @freeDom- 

thanks for this contribution 👍 
Please cover these new possible sentences with tests, so we can ensure, there are no regressions to existing sentences and all possible new sentences are covered and correct.
thx.

**Comment by freeDom-** [comment]
> Hi @freeDom-
> 
> thanks for this contribution 👍 Please cover these new possible sentences with tests, so we can ensure, there are no regressions to existing sentences and all possible new sentences are covered and correct. thx.

Added test coverage. Please re-trigger the build process

**Review by mib1185 — CHANGES_REQUESTED** [review]
we have 21 new test sentences for turn off, but only 13 for turn on.
would be great if the tests were "synchron" for turn on and off (_same amount and same syntax/sentence structure_)

**Comment by freeDom-** [comment]
> we have 21 new test sentences for turn off, but only 13 for turn on. would be great if the tests were "synchron" for turn on and off (_same amount and same syntax/sentence structure_)

That seems odd. I am sure that I added the same sentences and tests for both turn on and turn off, since I am already using these locally. Probably forgot to git add the changes for turn on or something got messed up there. I am going to have a look at it when I find the time.

Thanks for taking your time to review :)

**Comment by freeDom-** [comment]
I checked the files again and test cases do exist for the new sentences.. Sorry, I do not have the time to harmonize the tests, which have previously been different.. I am going to leave this PR stale and use my local changes instead.

**Pull request closed without merging**
