### PR TITLE
[RO] Refactoring some words

### PR DESCRIPTION
**Pull request by tetele**
Adding common phrases to contract the code a bit

### CODE REVIEW

**Comment by tetele** [comment]
@zubir2k may I ask why you have merged this PR?

**Comment by zubir2k** [comment]
> @zubir2k may I ask why you have merged this PR?

My bad, ive mistakenly merged it. Apologies 🙌

**Comment by zubir2k** [comment]
Out of curiosity.. i wanted to clarify.. was i been requested to review this? 😊

**Comment by arunshekher** [comment]
Yeah, _squash and merge_ does work apparently 😊. But I wonder why this open PR originally had commits that has already been merged to `main`.

**Comment by tetele** [comment]
I have not explicitly asked for review from anyone. Apparently, some commits were added incorrectly to my local dev branch after a pull, which tagged it with other languages than intended. Which, in turn, added you guys as reviewers.

However, if you can see that something's fishy, do you really just merge the branch? Don't you actually review before merging? And if so, how did you review the Romanian part, at least?

**Comment by arunshekher** [comment]
Agree, the PR submitter should have been asked/notified for explanation or left the PR alone for the maintainers to review when one see the the PR contained languages out of your purview. But I think the PR submitter also has the responsibility to check that the open PRs actually only contained what they really wanted to submit. Not everyone are well versed with Github.

**Comment by zubir2k** [comment]
Of course not 🤠

After getting the notice to review, I just run thru n see what were the changes being made. All checks were green and i tought this PR is pending for action and merging was the only available option. If this action is wrong, do accept my apologies.

Anyways, will further clarify in the future. 👌🏼

**Comment by arunshekher** [comment]
Could have just closed the PR here in Github while you were resolving the issues with your local feature branch.

**Pull request merged**
