### PR TITLE
Update homeassistant_HassTurnOn.yaml

### PR DESCRIPTION
**Pull request by kemo87**
added 2 sentences in czech language

### CODE REVIEW

**Comment by balloob** [comment]
Don't forget to add tests for the new sentences

**Comment by halecivo** [comment]
work already done in PR #479 , this one can be closed without merge

**Comment by halecivo** [comment]
work already done in PR #479 , this one can be closed without merge

**Comment by halecivo** [comment]
closing due to inactivity - work already done in different PR

**Pull request closed without merging**
