### PR TITLE
Add Brazilian(?) variations for current sentences

### PR DESCRIPTION
**Pull request by igorsantos07**
Not exactly sure if those are strictly Brazilian sentences, but they're definitely stuff I would hear around here :)

### CODE REVIEW

**Comment by leozanotto** [comment]
Probably you commitd on wrong files, the correct ones should be under pt-br folders not pt

**Comment by igorsantos07** [comment]
I actually committed when pt-br didn't even exist and I wasn't sure it
would 🤷🏼‍♂️

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by leozanotto** [comment]
> I actually committed when pt-br didn't even exist and I wasn't sure it would 🤷🏼‍♂️ but I guess I wasn't as fast/well connected as those who created the folder and didn't notice other Brazilian PRs.

I have created a PR right now, probably some of the changes you made are already there: #1146

**Comment by dclobato** [comment]
> I have created a PR right now, probably some of the changes you made are already there: #1146

Same regarding the PR #1111...

**Pull request closed without merging**
