### PR TITLE
[NE] Added Initial Support for Nepali Language

### PR DESCRIPTION
**Pull request by Rrp13**
Updated _common.yaml, homeassistant_HassTurnOff and homeassistant_HassTurnOn

### CODE REVIEW

**Comment by v1k70rk4** [comment]
Hi, we're glad you're here ;)

To keep a PR manageable, we break the work into smaller parts. This way, it's clear what has already been completed and what still needs to be done.

I suggest including only the files you've already completed in the PR:
HassTurnOff / HassTurnOn  
and the _fixtures.yaml / _common.yaml files.

**Comment by v1k70rk4** [comment]
And one more observation:  
The HassTurnOff/On is specifically for general cases, while for the examples you mentioned, there are already two separate parts: fan_HassTurnOff/On and light_HassTurnOff/On.  

It's worth starting from the English version and translating that.

**Comment by v1k70rk4** [comment]
Until a maintainer approves it, I checked if it would pass the test, and unfortunately, it doesn’t.  
=============================================== short test summary info ================================================  
FAILED tests/test_language_sentences.py::test_homeassistant_HassTurnOff[ne] - AssertionError: Recognition failed for 'बैठकको बत्ती निबाइदेउ न'  
FAILED tests/test_language_sentences.py::test_homeassistant_HassTurnOn[ne] - AssertionError: Recognition failed for 'बैठकको बत्ती बाल्देउ न'  
============================================ 2 failed, 101 passed in 11.88s ============================================  

This means that: The sentence "बैठकको बत्ती निबाइदेउ न" in its current form does not fit the given template because the verb type "निबाइदेउ" is not covered by the template. The template includes "निबाउनु", but "निबाइदेउ" is a conjugated, imperative form of that verb, which requests the action to be performed.

To make this fit, you would need to add the following variations to the template:

निबाइदेउ  
निबाइदिनुस  

This way, sentences like "बैठकको बत्ती निबाइदेउ न" and similar ones would match the pattern.

By the way, how did you get started with the translation? Windows/Linux/Visual Studio Core/Codespace? You can read about how to run tests on your own machine here. You’ll need it if you’re planning to take your language skills to the next level ;)

**Comment by Rrp13** [comment]
@v1k70rk4 Thanks again for your input. I will look into it. The specific thing that you mentioned is explicitly defined, and it should have worked. Could you please let me know which test you did so that I can figure out the issue. I am using vscode in linux.
I did the language validation test, and it passed.

**Comment by v1k70rk4** [comment]
If /script/test runs fine for you, then don’t worry :) My computer completely freaked out with the Nepali characters, so maybe the bug is on my end :) Just submit it as it is, and someone will review it soon.

**Comment by Rrp13** [comment]
I have rechecked and perfomed all the tests mentioned in the documents and all of them have passed for HassTurnOn and HassTurnOff. @v1k70rk4 Thank you for helping me out.

**Comment by synesthesiam** [comment]
Looks great, thank you!

**Pull request merged**
