### PR TITLE
Added lb HassGetState responses

### PR DESCRIPTION
**Pull request by mojikosu**

### CODE REVIEW

**Comment by synesthesiam** [comment]
@mojikosu Should be good to go when you're ready :+1:

**Comment by mojikosu** [comment]
@synesthesiam 
Heya,

I completed the tasks set out by you ;)
However a tiny issue remains.
Apparently, my local language for on/off is not tolerated in responses. The system expects the english on/off words. I created the in/out references in common.yaml.
Have I overlooked something?

**Comment by tetele** [comment]
Maybe this https://github.com/home-assistant/intents/pull/1001 ?

**Comment by mojikosu** [comment]
> Maybe this #1001 ?

Will give this a try! Cheers!

**Pull request merged**
