### PR TITLE
cs sentenses

### PR DESCRIPTION
**Pull request by schizza**
first commit to sentenses

### CODE REVIEW

**Comment by balloob** [comment]
All sentence contributions need to be accompanied by tests. To make contributions faster to review and approve, we want them to be limited to a single domain (cover, light, homeassistant)

**Comment by schizza** [comment]
All tests have passed.

testPass

**Comment by TomaszPilch** [comment]
@schizza tests should be sent in this PR too

**Comment by schizza** [comment]
Ok, will add to PR. Thanks.

**Pull request closed without merging**
