### PR TITLE
Fix "all" response grammar and include the state

### PR DESCRIPTION
**Pull request by vivobg**
### Before:
**Query**: "are all windows closed?"
**Answer**: "No, Living Room Window Left and Shed Window not"

**Query**: "are all water sensors wet?"
**Answer**: "No, Kitchen leak sensor not"

### After:
**Query**: "are all windows closed?"
**Answer**: "No, Living Room Window Left and Shed Window are not closed"

**Query**: "are all water sensors wet?"
**Answer**: "No, Kitchen leak sensor is not wet"

### CODE REVIEW

**Review by tetele — CHANGES_REQUESTED** [review]
Please don't mix things in the same PR. As you've seen, I've closed #1515 which would leave this PR hanging. You could leave just the response changes for `all`, although I believe there was a [good reason](https://developers.home-assistant.io/docs/voice/intent-recognition/style-guide#be-concise) for the brevity of the responses.

I will look back and get back on the reasons for avoiding more elaborate answers (such as those you are suggesting), but this PR is definitely not getting merged with the window states as well.

**Comment by vivobg** [comment]
Thank you for the review. I will make the requested changes later today.

**Review by tetele — APPROVED** [review]
Looks good to me, with the exception of when a queried entity has a plural name (e.g. `Christmas lights`), in which case the response would be `No, Christmas lights is not on` or something like that.

@synesthesiam is there any reason we wouldn't want to be just a little bit more specific in responses? I've thought about it for a bit and as long as the binary states do not depend on number/gender (as is the case in English), I don't see a reason not to make responses sound better/less robotic in most cases.

**Comment by tetele** [comment]
Thanks @vivobg

**Pull request merged**
