### PR TITLE
[en] Add definite article for object of HassTurnOn/HassTurnOff responses

### PR DESCRIPTION
**Pull request by HarvsG**
To me at least, it sounds much more natural with a "the" I.e "Turned on the light(s)"
Otherwise "lights turned on" sounds more natural than "turned on lights"

Side note:

>   Google's solution is answering in the present tense:
>   "OK Google turn on the kitchen lights" : "Sure, turning 4 lights on"
>   Or "OK Google, turn on the hallway lights" : "Sure, turning the hallway lights on"
>   
>   To me that sounds more natural, however there is a subtle difference, google's solution implies an attempt, but not that the action has been successful, Assist's response implies success.

In the meantime "the" is added.

### CODE REVIEW

**Review by tetele — CHANGES_REQUESTED** [review]
Fair enough, but you need to alter the expected responses in all tests, too.

**Comment by HarvsG** [comment]
> Fair enough, but you need to alter the expected responses in all tests, too.

Tests updated

**Review by tetele — CHANGES_REQUESTED** [review]
Please fix the failing tests

**Review by tetele — APPROVED** [review]
Thanks for this!

**Pull request merged**
